name: Run Scraper Weekly

on:
  schedule:
    # Runs every Thursday at midnight UTC
    - cron: "52 9 * * 0"
  workflow_dispatch: # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install requests

      - name: Run scraper
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
        run: python scripts/scraper.py

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: scraped-results
          path: results_*.csv
